const types = [
    { title: "Update", value: "update" },
    { title: "Feature", value: "feat" },
    { title: "Bug fix", value: "fix" },
    { title: "Documentation", value: "docs" },
    { title: "Refactoring", value: "refactor" },
    { title: "Code style", value: "style" },
    { title: "Performance", value: "perf" },
    { title: "Testing", value: "test" },
    { title: "Chore", value: "chore" },
    { title: "Build system", value: "build" },
    { title: "Continuous Integration", value: "ci" },
    { title: "Revert commit", value: "revert" },
    { title: "Deployment", value: "deploy" },
    { title: "Security fix", value: "security" },
    { title: "Work in progress", value: "wip" },
    { title: "Infrastructure", value: "infra" },
    { title: "Configuration", value: "config" },
    { title: "User Experience", value: "ux" },
    { title: "User Interface", value: "ui" },
    { title: "Logging", value: "log" },
    { title: "Database", value: "db" },
    { title: "Dependencies", value: "deps" },
    { title: "Localization", value: "l10n" },
    { title: "Hotfix", value: "hotfix" },
    { title: "Analytics", value: "analytics" },
    { title: "Error Handling", value: "error" },
    { title: "Accessibility", value: "accessibility" },
    { title: "Monitoring", value: "monitoring" },
    { title: "Mock Data", value: "mock" },
    { title: "Rollback", value: "rollback" },
    { title: "Experimental", value: "experiment" }
];

const scopes = [
    { title: "Authentication", value: "auth" },
    { title: "API", value: "api" },
    { title: "Database", value: "db" },
    { title: "User Interface", value: "ui" },
    { title: "User Experience", value: "ux" },
    { title: "Forms", value: "forms" },
    { title: "Tasks", value: "tasks" },
    { title: "Notifications", value: "notifications" },
    { title: "Dashboard", value: "dashboard" },
    { title: "Settings", value: "settings" },
    { title: "Billing", value: "billing" },
    { title: "Permissions", value: "permissions" },
    { title: "Continuous Integration", value: "ci" },
    { title: "Deployment", value: "deploy" },
    { title: "Dependencies", value: "dependencies" },
    { title: "Mobile", value: "mobile" },
    { title: "Desktop", value: "desktop" },
    { title: "Search", value: "search" },
    { title: "Filtering", value: "filter" },
    { title: "Onboarding", value: "onboarding" },
    { title: "Logging", value: "logs" },
    { title: "Themes", value: "theme" },
    { title: "Translations", value: "translations" },
    { title: "Reports", value: "reports" },
    { title: "Emails", value: "email" },
    { title: "Chat", value: "chat" },
    { title: "Artificial Intelligence", value: "ai" },
    { title: "Security", value: "security" },
    { title: "Error Handling", value: "error-handling" },
    { title: "Testing", value: "testing" }
];

module.exports = { scopes, types };

